export interface Video {
    id: number
    title: string
    description:string
    author: string
    thumbnail: string
    duration: string
    views: string
    date: string
    categories: string[]
  }
  
  const videos: Video[] = [
    {
      id: 1,
      title: "Advanced Video Editing Masterclass",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "Sarah Johnson",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "42:30",
      views: "8.5K",
      date: "2024-02-14",
      categories: ["Popular", "Video Creation"],
    },
    {
      id: 2,
      title: "Professional Lighting Techniques",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "Michael Chen",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "35:45",
      views: "12K",
      date: "2024-02-15",
      categories: ["Popular", "Video Creation"],
    },
    {
      id: 3,
      title: "Viral Video Creation Secrets",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "Alex Rivera",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "55:20",
      views: "250K",
      date: "2024-02-10",
      categories: ["Popular", "Marketing"],
    },
    {
      id: 4,
      title: "YouTube Algorithm Mastery",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "Emma Wilson",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "48:15",
      views: "180K",
      date: "2024-02-12",
      categories: ["Popular", "Marketing"],
    },
    {
      id: 5,
      title: "Social Media Video Marketing",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "David Kim",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "39:45",
      views: "145K",
      date: "2024-02-13",
      categories: ["Popular", "Marketing"],
    },
    {
      id: 6,
      title: "TikTok Content Strategy",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "Sophie Chen",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "32:20",
      views: "120K",
      date: "2024-02-14",
      categories: ["Popular", "Marketing"],
    },
    {
      id: 7,
      title: "Instagram Reels Masterclass",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "James Wilson",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "45:30",
      views: "98K",
      date: "2024-02-15",
      categories: ["Popular", "Marketing"],
    },
    {
      id: 8,
      title: "Camera Movement Basics",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "Emma Wilson",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "28:15",
      views: "6.2K",
      date: "2024-02-15",
      categories: ["Video Creation"],
    },
    {
      id: 9,
      title: "Color Grading Essentials",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "Alex Rivera",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "51:20",
      views: "9.8K",
      date: "2024-02-14",
      categories: ["Video Creation"],
    },
    {
      id: 10,
      title: "2D Animation Fundamentals",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "Emily Rodriguez",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "56:30",
      views: "8.9K",
      date: "2024-02-14",
      categories: ["Animation"],
    },
    {
      id: 11,
      title: "Character Animation Workshop",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "Marcus Lee",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "62:15",
      views: "7.3K",
      date: "2024-02-15",
      categories: ["Animation"],
    },
    {
      id: 12,
      title: "Motion Graphics Masterclass",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "Sarah Chen",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "48:40",
      views: "9.1K",
      date: "2024-02-13",
      categories: ["Animation"],
    },
    {
      id: 13,
      title: "Audio Mixing Basics",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "David Kim",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "41:20",
      views: "6.7K",
      date: "2024-02-15",
      categories: ["Sound Design"],
    },
    {
      id: 14,
      title: "Sound Effects Creation",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "Lisa Wong",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "35:45",
      views: "5.4K",
      date: "2024-02-14",
      categories: ["Sound Design"],
    },
    {
      id: 15,
      title: "Music Scoring for Video",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "John Smith",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "52:30",
      views: "7.8K",
      date: "2024-02-13",
      categories: ["Sound Design"],
    },
    {
      id: 16,
      title: "My First Tutorial Video",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "You",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "15:20",
      views: "234",
      date: "2024-02-10",
      categories: ["Your Videos"],
    },
    {
      id: 17,
      title: "Product Review - Camera Gear",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "You",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "22:45",
      views: "567",
      date: "2024-02-12",
      categories: ["Your Videos"],
    },
    {
      id: 18,
      title: "Behind the Scenes - Project X",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "You",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "18:30",
      views: "345",
      date: "2024-02-14",
      categories: ["Your Videos"],
    },
    {
      id: 19,
      title: "Advanced Editing Techniques",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "Sarah Johnson",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "45:15",
      views: "25K",
      date: "2024-02-08",
      categories: ["Favorites", "Video Creation"],
    },
    {
      id: 20,
      title: "Cinematic Lighting Guide",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "Michael Chen",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "38:20",
      views: "18K",
      date: "2024-02-09",
      categories: ["Favorites", "Video Creation"],
    },
    {
      id: 21,
      title: "Color Theory for Filmmakers",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "Emma Wilson",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "42:30",
      views: "15K",
      date: "2024-02-10",
      categories: ["Favorites", "Video Creation"],
    },
    {
      id: 22,
      title: "Advanced Camera Techniques",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "James Wilson",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "55:20",
      views: "12.3K",
      date: "2024-02-15",
      categories: ["Watch Later", "Video Creation"],
    },
    {
      id: 23,
      title: "Video Marketing Masterclass",
      description: "Quis culpa velit officia dolor nostrud est amet incididunt ipsum. Proident est et do dolore qui tempor sit dolor minim cillum. In laboris nostrud sint et amet velit sint eiusmod minim nulla est. Magna enim magna ad reprehenderit consequat. Eu magna aliqua fugiat velit anim adipisicing dolore quis fugiat officia.",
      author: "Lisa Thompson",
      thumbnail: "/placeholder.svg?height=200&width=350",
      duration: "68:45",
      views: "8.9K",
      date: "2024-02-14",
      categories: ["Watch Later", "Marketing"],
    },
  ]
  
  export default videos
  
  